# Generated by Django 6.0.3 on 2026-05-20 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ING', 'Ingreso'), ('EGR', 'Egreso')], max_length=3, verbose_name='Tipo de movimiento')),
                ('numero_planilla', models.CharField(help_text='Numeración automática: ING-0001, EGR-0001, etc.', max_length=20, unique=True, verbose_name='Número de planilla')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora del movimiento')),
                ('nombre_persona', models.CharField(help_text='Encargado que entrega el componente o persona que lo retira.', max_length=200, verbose_name='Nombre de la persona')),
                ('cedula', models.CharField(blank=True, help_text='Documento de identidad de la persona. Requerido en egresos.', max_length=20, verbose_name='Cédula / ID')),
                ('cargo', models.CharField(blank=True, help_text='Cargo o puesto de la persona.', max_length=100, verbose_name='Cargo')),
                ('departamento', models.CharField(blank=True, help_text='Departamento al que pertenece (solo para egresos).', max_length=100, verbose_name='Departamento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que registró el movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Cantidad de unidades involucradas en este movimiento.', verbose_name='Cantidad')),
                ('snapshot_nombre', models.CharField(max_length=200, verbose_name='Nombre (histórico)')),
                ('snapshot_categoria', models.CharField(max_length=100, verbose_name='Categoría (histórico)')),
                ('snapshot_marca', models.CharField(max_length=100, verbose_name='Marca (histórico)')),
                ('snapshot_modelo', models.CharField(max_length=100, verbose_name='Modelo (histórico)')),
                ('snapshot_serial', models.CharField(max_length=100, verbose_name='Serial (histórico)')),
                ('snapshot_detalles', models.TextField(blank=True, verbose_name='Detalles (histórico)')),
                ('snapshot_ubicacion', models.CharField(max_length=100, verbose_name='Ubicación (histórico)')),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_movimiento', to='inventory.componente', verbose_name='Componente')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='movements.movimiento', verbose_name='Movimiento')),
            ],
            options={
                'verbose_name': 'Detalle de movimiento',
                'verbose_name_plural': 'Detalles de movimientos',
                'ordering': ['movimiento', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo'], name='movements_m_tipo_f79472_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['fecha_hora'], name='movements_m_fecha_h_13ff58_idx'),
        ),
    ]
