# Generated by Django 6.0.3 on 2026-05-20 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre único que identifica la categoría (ej: "Procesadores").', max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del componente (ej: "Tarjeta gráfica NVIDIA RTX 4060").', max_length=200, verbose_name='Nombre del componente')),
                ('marca', models.CharField(help_text='Fabricante del componente (ej: "NVIDIA", "AMD", "Intel").', max_length=100, verbose_name='Marca')),
                ('modelo', models.CharField(help_text='Modelo específico del componente (ej: "RTX 4060 6GB").', max_length=100, verbose_name='Modelo')),
                ('serial', models.CharField(help_text='Identificador único del componente. No puede estar vacío ni repetirse.', max_length=100, unique=True, verbose_name='Número de serie')),
                ('detalles', models.TextField(blank=True, help_text='Información adicional: capacidad, velocidad, tipo de conexión, etc.', verbose_name='Detalles o especificaciones')),
                ('cantidad', models.PositiveIntegerField(default=0, help_text='Unidades disponibles actualmente en el almacén.', verbose_name='Cantidad disponible')),
                ('ubicacion', models.CharField(help_text='Posición física dentro del almacén (ej: "Estante A1", "Sección B3").', max_length=100, verbose_name='Ubicación en el almacén')),
                ('imagen', models.ImageField(blank=True, help_text='Fotografía o ilustración del componente. Opcional.', null=True, upload_to='componentes/', verbose_name='Imagen del componente')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se registró por primera vez en el sistema.', verbose_name='Fecha de ingreso')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de última actualización')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece este componente.', on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='inventory.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Componente',
                'verbose_name_plural': 'Componentes',
                'ordering': ['categoria', 'nombre'],
                'indexes': [models.Index(fields=['serial'], name='inventory_c_serial_5dcb3c_idx'), models.Index(fields=['categoria'], name='inventory_c_categor_81c569_idx')],
            },
        ),
    ]
